[build]
builder = "dockerfile"
dockerfilePath = "./HNG-Stage0-Api/Dockerfile"

# railway.toml
[build]
builder = "Dockerfile"

[env]
ASPNETCORE_ENVIRONMENT = "Production"
ConnectionStrings__DefaultConnection = "Data Source=/app/app.db"

[deploy]
startCommand = "dotnet HNG-Api1-2.dll"
